version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: ./db.dockerfile
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 55432:5432
    volumes:
      - ./docker_data/postgresql/data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./web.dockerfile
    container_name: party_finder_web
    # restart: always
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    ports:
      - 8088:8088
    volumes:
      - ./web:/root/web